### ISSUE TITLE
Unable to access preprocessing module 

### ISSUE THREAD

**Issue by Taydra-Low** [NOAA-GFDL/xwmt#5] opened 2022-06-21 16:31 UTC
When I import xwmt I am unable to access the preprocessing module. 

It shows that the preprocessing module is part of the package as shown below 
![image](https://user-images.githubusercontent.com/101355407/174847678-3114d1c4-72f4-44b5-90e7-b78a1aa57187.png)

But when I try to look into the preprocessing module or use the module I get an error. 
![image](https://user-images.githubusercontent.com/101355407/174848061-7523b39e-9670-4967-b9c9-426ecbbf240e.png)

However the swmt and compute modules work just fine. At the moment I have just done the preprocessing manually.
![image](https://user-images.githubusercontent.com/101355407/174850667-b63e0977-1083-4dad-8e3f-589059ace1d8.png)

Here are the software version I use: 
xarray version : 2022.3.0
dask version : 2022.05.0
numpy version : 1.21.6

**Comment by jetesdal** [comment] 2022-06-23 18:59
Hi @Taydra-Low! Thanks for documenting this issue. I can reproduce your error; when running `help(xwmt.preprocessing)`, I get the same response that "module 'xwmt' has no attribute 'preprocessing'". 

I am not sure why the `help()` command can't be called on `xwmt.preprocessing` directly. Maybe it is because we use the name "preprocessing" for both the submodule and the function. However, you should be able to load and use the `preprocessing` function after loading it separately with
`from xwmt import preprocessing`

And then you should be able to use `help(preprocessing)`

I created an example notebook that shows the usage of `preprocessing()`. You can view it [here](https://nbviewer.org/github/jetesdal/notebooks/blob/master/swmt_example.ipynb). If you want to run the notebook with the example data, you can download the data [here](https://drive.google.com/drive/folders/1euhD0ZRmTO-IyTeR41ktuGUcHdY5Riiw?usp=sharing)

Let me know if importing the `preprocessing` function separately allows you to use it or if there are any other issues.

**Comment by hdrake** [comment] 2023-04-26 19:20
This issue can be closed as the `preprocessing` module no longer exists.

**Comment by jetesdal** [comment] 2023-05-09 20:41
Thanks @hdrake. Closing this issue.

**Closed by jetesdal** 2023-05-09 20:41 UTC
